INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('bibi', '67', 'test1', 'bibi6666667@kakao.com');
INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('noname', '67', 'test2', 'non_named@naver.com');

INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (1, 1, 'test1', 'test1 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (2, 1, 'test2', 'test2 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (3, 1, 'test3', 'test3 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (4, 1, 'test4', 'test4 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (5, 1, 'test5', 'test5 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (6, 1, 'test6', 'test6 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (7, 1, 'test7', 'test7 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (8, 1, 'test8', 'test8 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (9, 1, 'test9', 'test9 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (10, 1, 'test10', 'test10 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (11, 1, 'test11', 'test11 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (12, 1, 'test12', 'test12 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (13, 1, 'test13', 'test13 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (14, 1, 'test14', 'test14 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (15, 1, 'test15', 'test15 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (16, 1, 'test16', 'test16 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (17, 1, 'test17', 'test17 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (18, 1, 'test18', 'test18 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (19, 1, 'test19', 'test19 contents', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (id, writer_id, title, contents, date_time) VALUES (20, 1, 'test20', 'test20 contents', CURRENT_TIMESTAMP());
